services:
  -type:web
  name:fastapi-ml-model
  runtime:python
  buildCommand:"pip install -r requirments.txt"
  startCommand:"uvicorn api.main:app --host 0.0.0.0 --port 10000"
  env:
    -key:port
    value:10000
  plan:free
  